/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef UNLUA_API
#define UNLUA_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern UNLUA_API FName UNLUA_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class UNLUA_API AUnLua : public AActor
{
public:
	APlayerPawn* AssignedPlayer;
	DECLARE_FUNCTION(execgetGlobalVariable);
	DECLARE_FUNCTION(execsetGlobalVariable);
    DECLARE_FUNCTION(execcompileScript);
    DECLARE_FUNCTION(execrunLuaScript);
    DECLARE_CLASS(AUnLua,AActor,0)
	AUnLua();
	UBOOL Tick(FLOAT fTime, ELevelTick TickType);
	void Destroy(void);
	lua_State* luaState;
};

#endif

AUTOGENERATE_FUNCTION(AUnLua,-1,execgetGlobalVariable);
AUTOGENERATE_FUNCTION(AUnLua,-1,execsetGlobalVariable);
AUTOGENERATE_FUNCTION(AUnLua,-1,execcompileScript);
AUTOGENERATE_FUNCTION(AUnLua,-1,execrunLuaScript);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
